### ISSUE TITLE
Scheduling pada google meet/zoom melalui Bluetape

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#10]
auto include jadwal kuliah ke calendar (google/sejenisnya), auto create schedule perkuliahan di zoom/meet selama 1 semester, request jadwal bertemu dari mahasiswa kepada dosen pembimbing, kemudian auto schedule zoom/meet

**Comment by pascalalfadian** [comment]
Sepertinya tidak perlu dibuat dulu, karena ranah nya BTI, dan saat ini BlueTape tidak memiliki kemampuan untuk integrasi dengan jadwal kuliah dari BTI.
