### ISSUE TITLE
Mengubah atau Membatalkan Permohonan untuk Dosen ataupun Mahasiswa

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#11]
mengubah atau membatalkan permohonan

**Comment by pascalalfadian** [comment]
ada tombol baru untuk mengedit ataupun mengubah. Jika diedit/diubah, TU akan mendapatkan notifikasi. Jika status sudah diapprove / dicetak / ditolak, tidak bisa lagi.

**Comment by stephenhadi** [comment]
sudah diimplementasi

**Comment by stephenhadi** [comment]
reopen. ketemu bug pada ubah permohonan. nama pemohon harusnya nama bukan email
![image](https://user-images.githubusercontent.com/54956908/118481644-e652b480-b73d-11eb-8abd-36814698c32e.png)

**Comment by stephenhadi** [comment]
dipindah ke issue #39
