### ISSUE TITLE
Memperbaiki Form dan Link yang tidak aktif

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#13]
Update form atau link (ada beberapa link yang tidak aktif, misal no surat, daftar ruang, peraturan/SK terus diupdate (perlu kerjasama dg pihak lain)); dibuat lebih sistematis (tampilannya tidak seragam); dibuat lebih interaktif (misal peminjaman ruang).

**Comment by pascalalfadian** [comment]
Sepertinya masukan ini mencakup di luar sistem BlueTape:

- no surat, daftar ruang, peraturan/SK, tidak termasuk dalam sistem BlueTape.
