### ISSUE TITLE
Mengintegrasi Bluetape dengan SSO UNPAR

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#14]
Fitur yang diharapkan : layanan BlueTape bisa terintegrasi secara penuh dengan StudentPortal (contoh : login dengan SSO, BlueTape dapat diakses lewat StudentPortal [bagian Pengajuan]) --> membentuk satu rangkaian layanan UNPAR.

**Comment by pascalalfadian** [comment]
Untuk saat ini tidak dapat dilakukan, karena perlu koordinasi yang kuat dengan BTI.
