### ISSUE TITLE
Notifikasi E-mail terhadap Mahasiswa saat Permintaan Selesai

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#17]
Notifikasi ke email mahasiswa setelah proses yang diajukan selesai

**Comment by pascalalfadian** [comment]
Jika ingin menggunakan GMail SMTP, pastikan opsi GMail "Allow unsecured apps" dinyalakan dulu.

**Comment by stephenhadi** [comment]
Setelah diperiksa Bluetape sudah memiliki fitur untuk membuat pesan ke request transkrip mahasiswa.
