### ISSUE TITLE
Halaman Histori dan Request Transkrip Terpisah

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#19]
histori permohonan sebaiknya di page terpisah tidak di satu page dengan request transkrip.

**Comment by pascalalfadian** [comment]
Mohon ditanyakan dulu alasannya mengapa.

**Comment by stephenhadi** [comment]
Alasan dari pemberi feeedback adalah lebih ke permasalahan ui design,agar tidak pusing melihatnya jika page dipisah

**Comment by pascalalfadian** [comment]
Kalau alasannya lebih ke arah UI, daripada dibuat halaman terpisah, lebih baik dibuat modal saja sehingga terlihat "terpisah", tapi bisa masih dalam 1 page yang sama, sehingga maintenance tidak lebih ribet.

Idenya: Tambahkan 1 tombol "Buat permohonan" yang jika diklik membuka halaman permohonan tersebut. Jika berhasil di satu modul, buat juga di modul lainnya.

**Comment by pascalalfadian** [comment]
OK, looks good. Thanks!

**Comment by stephenhadi** [comment]
sudah dikerjakan
