### ISSUE TITLE
Fitur Bahasa Indonesia dan Inggris

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#20]
fitur bahasa (indonesia / inggris / bilingual)

**Comment by pascalalfadian** [comment]
tolong ditanyakan alasannya juga.

**Comment by stephenhadi** [comment]
Alasan dari permintaan fitur tersebut adalah :

Jika dibutuhkan untuk transkrip nilai dalam bahasa inggris, dulu ada pilihannya tetapi hasil transkrip tetap bahasa indonesia

**Comment by pascalalfadian** [comment]
Fitur transkrip nilai bahasa Inggris diminta untuk dihapus oleh TU, kalau tidak salah sepertinya karena memang sudah tidak ada.
