### ISSUE TITLE
Pagination tidak terstyle dengan baik

### ISSUE THREAD

**Issue by pascalalfadian** [stephenhadi/BlueTape#22]
Hi @stephenhadi,

Saat mengexplore BlueTape, saya menemukan bug yang sebenarnya muncul saat skripsi sebelumnya, tapi minta tolong untuk perbaiki juga ya. Jadi untuk pagination seperti ini: [Screen Shot 2020-11-09 at 14 22 32](https://user-images.githubusercontent.com/5976057/98511375-2a4c9480-2297-11eb-9582-35e13bef94b6.png), itu ternyata belum distyle dengan [Bootstrap Pagination](https://getbootstrap.com/docs/4.5/components/pagination/).

Tolong diperbaiki juga ya. Biasanya terjadi di halaman "Manajemen xxx".

Trims.

**Comment by stephenhadi** [comment]
sudah dikerjakan
