### ISSUE TITLE
Format Datetimepicker tidak konsisten

### ISSUE THREAD

**Issue by pascalalfadian** [stephenhadi/BlueTape#23]
Hi @stephenhadi,

Saat saya mengexplore BlueTape, saya ketemu bug yang muncul dari skripsi sebelumnya, dan mohon untuk bantu perbaiki juga ya. Jadi di halaman entri perubahan kuliah: 
![Screen Shot 2020-11-09 at 14 25 55](https://user-images.githubusercontent.com/5976057/98511663-a3e48280-2297-11eb-8eb3-c22b28759bdf.png). Kalau kamu perhatikan:

1. "Dari Hari & Jam" formatnya "YYYY/MM/DD hh:mm"
2. "Menjadi Hari & Jam" formatnya "YYYY-MM-DD hh:mm"

Mohon dibuat konsisten, standar yang kita pakai adalah "YYYY-MM-DD hh:mm" untuk seluruh input tanggal dan waktu, karena kompatibel dengan MySQL.

Trims.

**Comment by stephenhadi** [comment]
sudah diimplementasi
