### ISSUE TITLE
Mahasiswa dengan NPM baru tidak dapat lihat jadwal dosen

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#5]
Mahasiswa dengan npm 2017730016 tidak bisa melihat jadwal dosen. Kemungkinan mahasiswa dengan format npm baru juga tidak dapat lihat jadwal dosen.

**Comment by pascalalfadian** [comment]
Untuk NPM 2017730016 sudah dikonfirmasi bisa. Untuk NPM format baru (yang diawali `618`) perlu deploy dulu baru bisa ditest.

**Comment by stephenhadi** [comment]
sudah dicoba pada https://bluetape.azurewebsites.net/
