### ISSUE TITLE
Menyediakan Forum pada Bluetape untuk Q&A

### ISSUE THREAD

**Issue by stephenhadi** [stephenhadi/BlueTape#9]
Halo... 
Untuk current feature rasanya tidak ada (atau belum terpikir, karena biasanya terpikir "ada kurang fungsi apa" itu ketika sering digunakan). Cuma memang saat ini, saya sedang memikirkan bagaimana mekanisme/caranya supaya BT ini dapat juga digunakan pada era daring skrg ini. Karena ketika masa kuliah luring, BT terbukti membantu alur kerja di TU. 
Pada masa daring saat ini, ketika semua hal disampaikan via media online/digital, salah satu yg terjadi adalah penumpukan inbox. Contoh kemarin, ketika momen FRS/PRS. Mahasiswa banyak kontak via email, akhirnya menumpuk. Ini baru terpikir oleh saya, apa mungkin BT ini dijadikan mini portal untuk semacam Q&A? Tentunya untuk ranah Akademik ya. Hmm, mungkin kasarnya seperti portal komersil monday.com itu, cm ini khusus tim kecil Akademik (hingga WD1).

**Comment by pascalalfadian** [comment]
Untuk saat ini sepertinya tidak dapat dibuat, karena untuk forum sebaiknya menggunakan aplikasi pihak ketiga yang sudah matang dibanding membuat dari nol. Ada Microsoft Teams atau Slack atau monday.com yang sebenarnya bisa digunakan, atas kebijakan dekanat.
